### PR TITLE
Use docker-options introduced by dokku 0.3.17

### PR DESCRIPTION
**Pull request by Flink**
Remove dependency to the link plugin

### CODE REVIEW

**Comment by msjyoo** [comment]
Thanks for the PR! Have you tested this personally? It looks good to me, I'll merge it after I check the new Dokku options out.

**Comment by Flink** [comment]
Yes I tested it quickly and it was working. But you should try it to be sure if you want :)

**Comment by msjyoo** [comment]
I'll take your word for it :) I'll have to test it all on a new release anyway.

**Comment by Flink** [comment]
Ok great, thanks! :)

**Pull request merged**
