### PR TITLE
Use `$PLUGIN_PATH` instead of `$(dirname $0)/../`

### PR DESCRIPTION
**Pull request by Flink**
As discussed in https://github.com/progrium/dokku/pull/1425 and https://github.com/progrium/dokku/pull/1428

### CODE REVIEW

**Comment by msjyoo** [comment]
Is this compatible with Dokku v0.3.26, or do you know what version the new environment variable will be available? I'll merge this when a new stable gets released with your patch.

**Comment by Flink** [comment]
Yes it’s compatible, `$PLUGIN_PATH` is used by pluginhook so it has been here for a long time :)

**Comment by msjyoo** [comment]
Just want to let you know, thank you so much for these contributions :+1: I don't use Dokku much any more so I can't afford to actively maintain this.

**Comment by Flink** [comment]
no problem, you’re welcome :)

**Pull request merged**
